from tools.ai_recommender import AIDesignRecommender
import logging

logger = logging.getLogger(__name__)

class RoomAnalyzer:
    """Tool for analyzing room images and extracting design elements."""

    def __init__(self):
        self.recommender = AIDesignRecommender()

    def analyze(self, image_path: str) -> dict:
        """Analyze a room image and identify key design elements."""
        try:
            # Use the recommender's vision capabilities for actual analysis
            ai_data = self.recommender.generate_design_suggestions(image_path, "modern")
            
            detected = ai_data.get("detected_elements", [])
            
            # Simple heuristic for room type based on detected elements
            room_type = "living_room"
            elements_str = " ".join(detected).lower()
            if any(x in elements_str for x in ["bed", "pillow", "sleep"]):
                room_type = "bedroom"
            elif any(x in elements_str for x in ["kitchen", "cook", "oven"]):
                room_type = "kitchen"
            elif any(x in elements_str for x in ["monitor", "keyboard", "office"]):
                room_type = "office"

            # Extract the actual recommendations generated by the T5 model
            recommendations = [f["item"] for f in ai_data.get("furniture_recommendations", [])]

            return {
                "image_path": image_path,
                "room_type": room_type,
                "dominant_colors": ai_data.get("color_schemes", ["neutral", "accent"]),
                "detected_furniture": detected,
                "recommendations": recommendations,
                "lighting": {"type": "natural", "intensity": "medium"},
                "style": "Modern"
            }
        except Exception as e:
            logger.error(f"Analysis failed: {e}")
            return {
                "image_path": image_path,
                "room_type": "living_room",
                "dominant_colors": ["grey", "white"],
                "detected_furniture": [],
                "lighting": {"type": "natural", "intensity": "low"},
                "style": "minimalist",
                "error": str(e)
            }
